version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: wget https://packages.couchbase.com/clients/c/repos/deb/couchbase.key
          name: Get Couchbase Key 
      - run:
          command: sudo apt-key add couchbase.key
          name: Add Couchbase Key to Trusted Package Keys
      - run:
          command: echo "deb https://packages.couchbase.com/clients/c/repos/deb/ubuntu1604 xenial xenial/main" | sudo tee -a /etc/apt/sources.list
          name: Append couchbase repo to /etc/apt/sources.list
      - run:
          command: sudo apt-get update
          name: Refresh the APT cache
      - run:
          command: sudo apt-cache search libcouchbase
          name: Search the APT cache for libcouchbase
      - run:
          command: sudo apt-get install libcouchbase3 libcouchbase3-dev libcouchbase3-tools libcouchbase-dbg libcouchbase3-libev libcouchbase3-libevent
          name: Install libcouchbase
      - python/install-deps
      - python/save-cache
      - run:
          command: ./run_tests.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
