version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: sudo apt-get install libcouchbase
          name: Install libcouchbase
      - python/install-deps
      - python/save-cache
      - run:
          command: ./run_tests.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
